# Generated by Django 2.0.2 on 2018-02-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
