# Generated by Django 2.0.2 on 2018-02-26 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodle', '0006_auto_20180226_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('enrolltime', models.DateTimeField(auto_now=True)),
                ('relcourse', models.ManyToManyField(to='moodle.Course')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
