# Generated by Django 2.0.2 on 2018-02-26 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_enrolltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolltime',
            name='relcourse',
        ),
        migrations.AddField(
            model_name='enrolltime',
            name='relcourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moodle.Course'),
            preserve_default=False,
        ),
    ]
