# Generated by Django 2.0.2 on 2018-02-26 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0008_auto_20180226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='limit',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
